insert into `tip` (`id`, `name`, `fun_name`, `code`, `message`) values('1','散客','无限制次数','pass','欢迎莅临');
insert into `tip` (`id`, `name`, `fun_name`, `code`, `message`) values('2','散客','此卡无效','nopass','此卡无效');
insert into `tip` (`id`, `name`, `fun_name`, `code`, `message`) values('3','会员','','user','会员卡');
insert into `tip` (`id`, `name`, `fun_name`, `code`, `message`) values('4','员工','','worker','员工卡');
insert into `tip` (`id`, `name`, `fun_name`, `code`, `message`) values('5','月票卡','','month','月票卡');
insert into `tip` (`id`, `name`, `fun_name`, `code`, `message`) values('6','培训卡','','train','培训卡，剩余次数:[次数]');
insert into `tip` (`id`, `name`, `fun_name`, `code`, `message`) values('7','月票卡','','passmonth','上次使用时间未超过[小时]小时');
insert into `tip` (`id`, `name`, `fun_name`, `code`, `message`) values('8','培训卡','','passtrain','没有权限');
insert into `tip` (`id`, `name`, `fun_name`, `code`, `message`) values('10','培训卡','','passtime','上次使用时间未超过[小时]小时');
